# ========================
# Development Dockerfile
# ========================
FROM node:20-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

ENV NEXT_PUBLIC_MODE=devDocker

ENV HOST=0.0.0.0
ENV PORT=5000
EXPOSE 5000

CMD ["npm", "run", "dev"]
